### ISSUE TITLE
Missing temp variable while compiling a function which calls another one

### ISSUE THREAD

**Issue by Zifzaf** [spcl/dace#1139]
**Describe the bug**
I try to run the following code which is one benchmark take from npbench. When calling compile() on the mandelbrot function I get the error shown below. 

```
# -----------------------------------------------------------------------------
# From Numpy to Python
# Copyright (2017) Nicolas P. Rougier - BSD license
# More information at https://github.com/rougier/numpy-book
# -----------------------------------------------------------------------------

import numpy as np
import dace as dc

XN, YN, M, N = (dc.symbol(s, dtype=dc.int64) for s in ['XN', 'YN', 'M', 'N'])


@dc.program
def mgrid(X: dc.int64[M, N], Y: dc.int64[M, N]):
    for i in range(M):
        X[i, :] = i
    for j in range(N):
        Y[:, j] = j


@dc.program
def linspace(start: dc.float64, stop: dc.float64, X: dc.float64[N]):
    dist = (stop - start) / (N - 1)
    for i in dace.map[0:N]:
        X[i] = start + i * dist


@dc.program
def mandelbrot(xmin: dc.float64, xmax: dc.float64, ymin: dc.float64,
               ymax: dc.float64, maxiter: dc.int64, horizon: dc.float64):
    # Adapted from
    # https://thesamovar.wordpress.com/2009/03/22/fast-fractals-with-python-and-numpy/
    Xi = np.ndarray((XN, YN), dtype=np.int64)
    Yi = np.ndarray((XN, YN), dtype=np.int64)
    mgrid(Xi, Yi)
    X = np.ndarray((XN, ), dtype=np.float64)
    Y = np.ndarray((YN, ), dtype=np.float64)
    linspace(xmin, xmax, X)
    linspace(ymin, ymax, Y)
    # C = np.reshape(X, (xn, 1)) + Y * 1j
    C = np.ndarray((XN, YN), dtype=np.complex128)
    for i, j in dc.map[0:XN, 0:YN]:
        C[i, j] = X[i] + Y[j] * 1j
    N_ = np.zeros(C.shape, dtype=np.int64)
    Z_ = np.zeros(C.shape, dtype=np.complex128)
    # Xiv = np.ndarray((XN * YN,), dtype=np.int64)
    Xiv = np.reshape(Xi, (XN * YN, ))
    # Yiv = np.ndarray((XN * YN,), dtype=np.int64)
    Yiv = np.reshape(Yi, (XN * YN, ))
    # Cv = np.ndarray((XN * YN,), dtype=np.complex128)
    Cv = np.reshape(C, (XN * YN, ))

    Z = np.zeros(Cv.shape, np.complex128)
    I = np.ndarray((XN * YN, ), dtype=np.bool_)
    length = XN * YN
    k = 0
    while length > 0 and k < maxiter:
        # for k in range(maxiter):
        #     if length <= 0:
        #         break

        # Compute for relevant points only
        Z[:length] = np.multiply(Z[:length], Z[:length])
        Z[:length] = np.add(Z[:length], Cv[:length])

        # Failed convergence
        I[:length] = np.absolute(Z[:length]) > horizon
        for j in range(length):
            if I[j]:
                N_[Xiv[j], Yiv[j]] = k + 1
        for j in range(length):
            if I[j]:
                Z_[Xiv[j], Yiv[j]] = Z[j]

        # Keep going with those who have not diverged yet
        I[:length] = np.logical_not(
            I[:length])  # np.negative(I, I) not working any longer
        count = 0
        # for j in range(length):
        #     if I[j]:
        #         Z[count] = Z[j]
        #         count += 1
        # count = 0
        # for j in range(length):
        #     if I[j]:
        #         Xiv[count] = Xiv[j]
        #         Yiv[count] = Yiv[j]
        #         count += 1
        # count = 0
        # for j in range(length):
        #     if I[j]:
        #         Cv[count] = Cv[j]
        #         count += 1
        for j in range(length):
            if I[j]:
                Z[count] = Z[j]
                Xiv[count] = Xiv[j]
                Yiv[count] = Yiv[j]
                Cv[count] = Cv[j]
                count += 1
        length = count
        k += 1
    return Z_.T, N_.T


cm = mandelbrot.compile()
```

Error:
```
Exception raised while parsing DaCe program:
  in File "/home/andreas/Desktop/Studies-Git/PHPC/Mandelbrot/mandelbrot2_dace.py", line 38
    linspace(xmin, xmax, X)
Traceback (most recent call last):
  File "/home/andreas/Desktop/Studies-Git/PHPC/Mandelbrot/mandelbrot2_dace.py", line 106, in <module>
    cm = mandelbrot.compile()
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/parser.py", line 256, in compile
    sdfg = self._parse(args, kwargs, simplify=simplify, save=save)
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/parser.py", line 455, in _parse
    sdfg, cached = self._generate_pdp(args, kwargs, simplify=simplify)
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/parser.py", line 838, in _generate_pdp
    sdfg = newast.parse_dace_program(self.name,
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 209, in parse_dace_program
    sdfg, _, _, _ = visitor.parse_program(preprocessed_ast.preprocessed_ast.body[0])
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 1188, in parse_program
    self.visit_TopLevel(stmt)
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/astutils.py", line 471, in visit_TopLevel
    getattr(self, "visit_TopLevel" + clsname)(node)
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 4406, in visit_TopLevelExpr
    self.visit_Call(node.value)
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 4235, in visit_Call
    return self._parse_sdfg_call(funcname, func, node)
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 3881, in _parse_sdfg_call
    nsdfg = state.add_nested_sdfg(sdfg,
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/sdfg/state.py", line 1103, in add_nested_sdfg
    symbols = sdfg.free_symbols
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/sdfg/sdfg.py", line 1218, in free_symbols
    free_syms |= state.free_symbols
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/sdfg/state.py", line 420, in free_symbols
    freesyms |= set(map(str, n.desc(sdfg).free_symbols))
  File "/home/andreas/.local/lib/python3.10/site-packages/dace/sdfg/nodes.py", line 263, in desc
    return sdfg.arrays[self.data]
KeyError: '__tmp4'
```

**To Reproduce**
run 'python filename.py' on a file containing the code shown above.

**Expected behavior**
As I would expect the code to trace the function calls and compile the whole function.

**Desktop (please complete the following information):**
 Ubuntu 22.10 with python 3.10

**Comment by alexnick83** [comment]
Thank you for reporting this. Could you also confirm that `automatic_simplification` is enabled? If you are unsure what this is, it is on (by default). A temporary workaround is the following code snippet, which is also what NPBench does automatically with the `dace_cpu` and `dace_gpu` frameworks:
```python
sdfg = mandelbrot.to_sdfg(simplify=False)
sdfg.simplify()
cm = sdfg.compile()
```

**Comment by tbennun** [comment]
This is one of the stranger bugs I encountered. Shortest reproducer:

```python
import numpy as np
import dace

XN = dace.symbol('XN')
YN = dace.symbol('YN')
N = dace.symbol('N')

@dace.program
def nester(start: dace.float64, stop: dace.float64, X: dace.float64[N]):
    dist = (stop - start) / (N - 1)
    for i in dace.map[0:N]:
        X[i] = start + i * dist


@dace.program
def tester(xmin: dace.float64, xmax: dace.float64):
    a = np.ndarray((XN, YN), dtype=np.int64)
    b = np.ndarray((XN, YN), dtype=np.int64)
    c = np.ndarray((XN, ), dtype=np.float64)
    nester(xmin, xmax, c)

tester.compile()
```
