### ISSUE TITLE
code that worked with DaCe stopped working

### ISSUE THREAD

**Issue by TheRand0m1z3r** [spcl/dace#1151]
**Describe the bug**
About  half a year ago, I wrote a piece of code and parallelized it using DaCe. For some reason, it has stopped working and now pops the error:
```
C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe D:\GitHub\dplus-dev\PythonInterface\dplus\g_r.py 
C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\frontend\python\newast.py:4295: UserWarning: Performance warning: Automatically creating callback to Python interpreter from method "numpy_random_normal". If you would like to know why parsing failed, please place a @dace.program decorator on the function. If a DaCe function cannot be provided (for example, due to recursion), register a replacement through "dace.frontend.common.op_repository".
  warnings.warn('Performance warning: Automatically creating '
WARNING: Passing int32 array argument "u" to a float64 array
WARNING: Passing int32 array argument "u" to a float64 array
WARNING: Passing int32 array argument "u" to a float64 array
WARNING: Passing int32 array argument "u" to a float64 array
Exception ignored on calling ctypes callback function: functools.partial(<function callback.get_trampoline.<locals>.trampoline at 0x0000023B2210ACA0>, <built-in method normal of numpy.random.mtrand.RandomState object at 0x0000023B752A1C40>, [0, 1], [(<class 'ctypes.c_double'>, (V, 4)), (<class 'ctypes.c_double'>, (4,))], [2], [(<class 'ctypes.c_double'>, (V, 4))])
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\dtypes.py", line 1077, in trampoline
    ret = orig_function(*list_of_other_inputs)
  File "mtrand.pyx", line 1510, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 594, in numpy.random._common.cont
  File "_common.pyx", line 499, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 384, in numpy.random._common.check_array_constraint
ValueError: scale < 0
Exception ignored on calling ctypes callback function: functools.partial(<function callback.get_trampoline.<locals>.trampoline at 0x0000023B2210A790>, <built-in method normal of numpy.random.mtrand.RandomState object at 0x0000023B752A1C40>, [0, 1], [(<class 'ctypes.c_double'>, (V, 4)), (<class 'ctypes.c_double'>, (4,))], [2], [(<class 'ctypes.c_double'>, (V, 4))])
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\dtypes.py", line 1077, in trampoline
    ret = orig_function(*list_of_other_inputs)
  File "mtrand.pyx", line 1510, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 594, in numpy.random._common.cont
  File "_common.pyx", line 499, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 384, in numpy.random._common.check_array_constraint
ValueError: scale < 0
Exception ignored on calling ctypes callback function: functools.partial(<function callback.get_trampoline.<locals>.trampoline at 0x0000023B22125EE0>, <built-in method normal of numpy.random.mtrand.RandomState object at 0x0000023B752A1C40>, [0, 1], [(<class 'ctypes.c_double'>, (V, 4)), (<class 'ctypes.c_double'>, (4,))], [2], [(<class 'ctypes.c_double'>, (V, 4))])
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\dtypes.py", line 1077, in trampoline
    ret = orig_function(*list_of_other_inputs)
  File "mtrand.pyx", line 1510, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 594, in numpy.random._common.cont
  File "_common.pyx", line 499, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 384, in numpy.random._common.check_array_constraint
ValueError: scale < 0
Exception ignored on calling ctypes callback function: functools.partial(<function callback.get_trampoline.<locals>.trampoline at 0x0000023B221250D0>, <built-in method normal of numpy.random.mtrand.RandomState object at 0x0000023B752A1C40>, [0, 1], [(<class 'ctypes.c_double'>, (V, 4)), (<class 'ctypes.c_double'>, (4,))], [2], [(<class 'ctypes.c_double'>, (V, 4))])
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\dtypes.py", line 1077, in trampoline
    ret = orig_function(*list_of_other_inputs)
  File "mtrand.pyx", line 1510, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 594, in numpy.random._common.cont
  File "_common.pyx", line 499, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 384, in numpy.random._common.check_array_constraint
ValueError: scale < 0
Exception ignored on calling ctypes callback function: functools.partial(<function callback.get_trampoline.<locals>.trampoline at 0x0000023B2210A700>, <built-in method normal of numpy.random.mtrand.RandomState object at 0x0000023B752A1C40>, [0, 1], [(<class 'ctypes.c_double'>, (V, 4)), (<class 'ctypes.c_double'>, (4,))], [2], [(<class 'ctypes.c_double'>, (V, 4))])
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\dtypes.py", line 1077, in trampoline
    ret = orig_function(*list_of_other_inputs)
  File "mtrand.pyx", line 1510, in numpy.random.mtrand.RandomState.normal
  File "_common.pyx", line 594, in numpy.random._common.cont
  File "_common.pyx", line 499, in numpy.random._common.cont_broadcast_2
  File "_common.pyx", line 384, in numpy.random._common.check_array_constraint
ValueError: scale < 0
WARNING: Passing int32 array argument "u" to a float64 array
C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\frontend\python\newast.py:4295: UserWarning: Performance warning: Automatically creating callback to Python interpreter from method "numpy_random_randint". If you would like to know why parsing failed, please place a @dace.program decorator on the function. If a DaCe function cannot be provided (for example, due to recursion), register a replacement through "dace.frontend.common.op_repository".
  warnings.warn('Performance warning: Automatically creating '
Traceback (most recent call last):
  File "D:\GitHub\dplus-dev\PythonInterface\dplus\g_r.py", line 649, in <module>
    my_g_r = g_r_from_model(file_single, Lx, Ly, Lz, thermal=1, Number_for_average_conf=5)
  File "D:\GitHub\dplus-dev\PythonInterface\dplus\g_r.py", line 486, in g_r_from_model
    return compute_gr(bins, thermal, vec_old, Lx, Ly, Lz, file_triple,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\frontend\python\parser.py", line 423, in __call__
    binaryobj = sdfg.compile(validate=self.validate)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\sdfg\sdfg.py", line 2189, in compile
    program_objects = codegen.generate_code(sdfg, validate=validate)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\codegen\codegen.py", line 227, in generate_code
    (global_code, frame_code, used_targets, used_environments) = frame.generate_code(sdfg, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dace\codegen\targets\framecode.py", line 802, in generate_code
    raise TypeError(f'Type inference failed for symbol {isvarName}')
TypeError: Type inference failed for symbol __tmp2
```

**To Reproduce**
This is the code in question:
```
V = dc.symbol('V')
M = dc.symbol('M')
TV = dc.symbol('TV')
NFC = dc.symbol('NFC')

def triple(mat_single, Lx, Ly, Lz):

    ms = mat_single.shape[0] #: dc.int64
    mat_triple = np.zeros([27*ms, 4]) #: dc.float64[27*n, 4]
    trans = np.array([-1, 0, 1])
    for i in range(3):
        for j in range(3):
            for k in range(3):
                it = int((9 * i + 3 * j + k)*ms)
                itpn = int((9 * i + 3 * j + k + 1)*ms)
                mat_triple[it:itpn] = mat_single + np.array([trans[i] * Lx, trans[j] * Ly, trans[k] * Lz, .0])
    return mat_triple

def g_r_from_model(file: str, Lx: dc.float64, Ly: dc.float64, Lz: dc.float64, file_triple: str =
r'.\my_triple', radius: dc.float64 = 0, r_max: dc.float64 = 15, dr: dc.float64 = 0.01,
                   Number_for_average_atoms: dc.int64 = 1
                   , thermal: dc.bool = 0, u: dc.float64[4] = np.array([0, 0, 0, 0]),
                   Number_for_average_conf: dc.int64 = 1):

    vec, n = read_from_file(file, radius)
    vec = np.copy(vec)
    if not thermal:
        vec_triple = np.zeros([1, 27 * n, 4])
        vec_triple[0] = triple(vec, Lx, Ly, Lz)#, file_triple)
    elif Number_for_average_conf != 1:
        vec_triple = np.zeros([Number_for_average_conf, 27 * n, 4])
        for conf in range(Number_for_average_conf):
            vec = thermalize(np.copy(vec), u)
            vec_triple[conf] = triple(vec, Lx, Ly, Lz)
    else:
        vec_triple = np.zeros([Number_for_average_conf, 27*n, 4])
        for conf in range(Number_for_average_conf):
            vec = thermalize(np.copy(vec), u)
            vec_triple[conf] = triple(vec, Lx, Ly, Lz)
    vec_old = np.copy(vec)

    bins = np.arange(0, r_max + dr, dr)
    return compute_gr(bins, thermal, vec_old, Lx, Ly, Lz, file_triple,
                      vec_triple, vec, radius, u, dr, r_max,
                      Number_for_average_atoms=Number_for_average_atoms,
                      Number_for_average_conf=Number_for_average_conf)

Number_for_average_atoms = dc.symbol('Number_for_average_atoms')
Number_for_average_conf = dc.symbol('Number_for_average_conf')

@dc.program(auto_optimize=True)
def compute_gr(bins: dc.float64[M], thermal: dc.bool, vec_old: dc.float64[V, 4], Lx: dc.float64, Ly: dc.float64,
               Lz: dc.float64, file_triple: str, vec_triple: dc.float64[NFC, TV, 4], vec: dc.float64[V, 4], radius=0,
               u: dc.float64[4]=np.array([0, 0, 0, 0]), dr=0.01, r_max=15):
    rho: dc.float64
    g_r = np.zeros([Number_for_average_atoms * Number_for_average_conf, M])

    num = 0
    it_tot = 0
    it_conf = 0

    while it_conf < NFC:#Number_for_average_conf:
        it_atom = 0
        while it_atom < Number_for_average_atoms:
            my_rand: dc.int64 = np.random.randint(0, V)
            r_0 = vec[my_rand]

            if radius == 0:
                for j in range(vec_triple.shape[1]):
                    row_j = vec_triple[it_conf, j]
                    d = np.sqrt((row_j[0] - r_0[0]) ** 2 + (row_j[1] - r_0[1]) ** 2 + (row_j[2] - r_0[2]) ** 2)
                    if (r_max < d) | (d < 1e-10):
                        continue
                    num += 1
                    for i in range(M):
                        if bins[i] < d:
                            pass
                        else:
                            if bins[i] >= d:
                                g_r[it_tot, i] += 1
                                break
            else:
                for j in range(vec_triple.shape[1]):
                    row = vec_triple[it_conf, j]
                    d = np.sqrt((row[0] - r_0[0]) ** 2 + (row[1] - r_0[1]) ** 2 + (row[2] - r_0[2]) ** 2)
                    r = row[3]
                    d_min = d - r
                    d_max = d + r
                    vol_tot = 4 * np.pi * r ** 3 / 3
                    nn = dc.int64(N_R(r, dr))

                    if (r_max < d_min) | (d < 1e-10):
                        pass
                    num += 1

                    for i in range(M):
                        if bins[i] < d_min:
                            pass
                        else:
                            if bins[i] > d_max:
                                g_r[0, i] += 1
                                break
                            else:
                                counted_vol = 0
                                for k in range(nn[0]):
                                    if i + k < M:
                                        if bins[i + k] < d_max:
                                            Vol = Lens_Vol(bins[i + k], r, d) - counted_vol
                                            g_r[it_tot, i + k] += Vol / vol_tot
                                            counted_vol += Vol
                                        else:
                                            g_r[it_tot, i + k] += 1 - counted_vol / vol_tot
                                    else:
                                        break
                                break

            rho_temp = 3 * np.sum(g_r[it_tot]) / (4 * np.pi * bins[-1] ** 3)
            g_r[it_tot, 1:] /= (rho_temp * 4 / 3 * np.pi * (bins[1:] ** 3 - bins[:-1] ** 3))
            it_tot += 1
            it_atom += 1
        it_conf += 1

    g_r[:] = np.sum(g_r) / (Number_for_average_atoms * Number_for_average_conf)
    rho = 3 * np.sum(g_r) / (4 * np.pi * bins[-1] ** 3)

    return bins, g_r, rho

if __name__ == '__main__':
    file_single = r'.\thermal_cube.dol'
    vec, n = read_from_file(file_single, 0.01)
    Lx = 50
    Ly = 50
    Lz = 50

    fskndf = g_r_from_model(file_single, Lx, Ly, Lz, thermal=1, Number_for_average_conf=5)
```
I added the needed file to run this (.txt needs to be changed to .dol)
[Cube.txt](https://github.com/spcl/dace/files/10003980/Cube.txt)

Thanks for the help!

**Comment by alexnick83** [comment]
Thank you for reporting this. We are looking into the issue, but it will take a few days to get back to you with a fix because we are currently attending SC'22.

**Comment by TheRand0m1z3r** [comment]
No worries with the delay :)
Thank you very much for the help, I will run and check using the `fix-unflatten-instruction` branch and update accordingly.

**Comment by TheRand0m1z3r** [comment]
UPDATE: Using the branch I was able to run the code with the suggested changes and it worked like a charm! 
Thanks a lot!

**Comment by alexnick83** [comment]
You are welcome! Let us know if you need further support.
