### ISSUE TITLE
`np.bool` has been deprecated (removed)

### ISSUE THREAD

**Issue by salehjg** [spcl/dace#1273]
**Describe the bug**
Runnin the sample code `samples/simple/axpy.py` fails with:
```
/usr/lib/python3.11/site-packages/dace/dtypes.py:153: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  numpy.bool: "bool",
Traceback (most recent call last):
  File "/run/media/saleh/DataNVMe/01_workspace/dace-samples/simple/axpy.py", line 5, in <module>
    import dace
  File "/usr/lib/python3.11/site-packages/dace/__init__.py", line 4, in <module>
    from .dtypes import *
  File "/usr/lib/python3.11/site-packages/dace/dtypes.py", line 153, in <module>
    numpy.bool: "bool",
    ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

Process finished with exit code 1
```

**To Reproduce**
Since `dace/dtypes.py` is used internally, any `import dace` will reproduce the error.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser -
 - Version -

Python 3.11.3
Numpy 1.24.3
Dace 0.10.0
(installed with `pip`)

**Comment by tbennun** [comment]
This bug was fixed in a later release, but Python 3.11 isn’t officially supported yet. It looks like PyPI installs a much older version in this case (we are at 0.14.3 at the moment). We will see how to fix it, thank you for reporting.

**Comment by tbennun** [comment]
@phschaad @alexnick83  what do you think of changing the CI pipeline from 3.10 to 3.11 and adding official support if it passes?

**Comment by alexnick83** [comment]
Python 3.11 should work with no issues.

**Comment by salehjg** [comment]
Tried to install the latest version with pip and as @tbennun mentioned, seems like Python3.11 is not supported.
Although, I am not sure why I ended up having `0.10.0` installed by `pip`:
```
pip install dace==0.14.3

ERROR: Ignored the following versions that require a different Python version: 
0.10.8 Requires-Python >=3.6, <3.9;
0.11.0 Requires-Python >=3.6, <3.10; 
0.11.1 Requires-Python >=3.6, <3.10; 
0.11.2 Requires-Python >=3.6, <3.10; 
0.11.3 Requires-Python >=3.6, <3.10; 
0.11.4 Requires-Python >=3.6, <3.11; 
0.12 Requires-Python >=3.6, <3.11; 
0.13 Requires-Python >=3.6, <3.11; 
0.13.1 Requires-Python >=3.6, <3.11; 
0.13.2 Requires-Python >=3.6, <3.11; 
0.13.3 Requires-Python >=3.6, <3.11; 
0.14 Requires-Python >=3.6, <3.11; 
0.14.1 Requires-Python >=3.6, <3.11; 
0.14.2 Requires-Python >=3.6, <3.11; 
0.14.3 Requires-Python >=3.6, <3.11
ERROR: Could not find a version that satisfies the requirement dace==0.14.3 (from versions: 0.8.0, 0.8.1, 0.9.0, 0.9.5, 0.10.0)
ERROR: No matching distribution found for dace==0.14.3
```

**Comment by tbennun** [comment]
I made a PR adding and testing support for Python 3.11. If everything passes we should release a new minor release on PyPI that fixes the issue.

**Comment by tbennun** [comment]
@salehjg Please try again with version 0.14.4, which should support Python 3.11.

**Comment by tbennun** [comment]
I think this is because your older installation also installed an outdated version of sympy. Try updating it with pip.
