### ISSUE TITLE
not-strictly-transformed sdfg does not compile

### ISSUE THREAD

**Issue by PanicSheep** [spcl/dace#142]
**Describe the bug**
Compiling this SDFG produces an error.
But first applying strict transformations an then compiling produces the desired output.

**To Reproduce**
Steps to reproduce the error:
1. Load SDFG from file [k_storage_expanded.zip](https://github.com/spcl/dace/files/4250012/k_storage_expanded.zip)
2. `sdfg.compile(optimizer="")`

Steps to reproduce the workaround:
1. Load SDFG from file [k_storage_expanded.zip](https://github.com/spcl/dace/files/4250012/k_storage_expanded.zip)
2. `sdfg.apply_strict_transformations()`
3. `sdfg.compile(optimizer="")`

**Expected behavior**
Get programs with the same output with and without `sdfg.apply_strict_transformations()`.

**Desktop**
 - Ubuntu 18.04.4 LTS
 - https://github.com/spcl/dace/pull/137

**Comment by tbennun** [comment]
What is the error that is produced?

**Comment by PanicSheep** [comment]
Traceback (most recent call last):
  File "/home/dominic/work/dawn2dace/src/synthetic_stencils_test.py", line 293, in test_3_numerically
    sdfg = sdfg.compile(optimizer="")
  File "/home/dominic/work/dace/dace/sdfg.py", line 1681, in compile
    program_objects = codegen.generate_code(sdfg)
  File "/home/dominic/work/dace/dace/codegen/codegen.py", line 140, in generate_code
    used_environments) = frame.generate_code(sdfg, None)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 926, in generate_code
    set(states_topological), states_generated, generated_edges)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 377, in generate_states
    callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 437, in dispatch_state
    sdfg, state, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 271, in generate_state
    skip_entry_node=False)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 468, in dispatch_subgraph
    state_id, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 516, in dispatch_scope
    sdfg, sub_dfg, state_id, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 136, in generate_scope
    skip_entry_node=True)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 475, in dispatch_subgraph
    callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 506, in dispatch_node
    sdfg, dfg, state_id, node, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 148, in generate_node
    gen(sdfg, dfg, state_id, node, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 1327, in _generate_NestedSDFG
    node.sdfg, node.schedule, sdfg_label)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 926, in generate_code
    set(states_topological), states_generated, generated_edges)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 377, in generate_states
    callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 437, in dispatch_state
    sdfg, state, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 271, in generate_state
    skip_entry_node=False)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 475, in dispatch_subgraph
    callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 506, in dispatch_node
    sdfg, dfg, state_id, node, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 148, in generate_node
    gen(sdfg, dfg, state_id, node, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 1327, in _generate_NestedSDFG
    node.sdfg, node.schedule, sdfg_label)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 926, in generate_code
    set(states_topological), states_generated, generated_edges)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 377, in generate_states
    callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 437, in dispatch_state
    sdfg, state, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/framecode.py", line 271, in generate_state
    skip_entry_node=False)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 468, in dispatch_subgraph
    state_id, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 516, in dispatch_scope
    sdfg, sub_dfg, state_id, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 136, in generate_scope
    skip_entry_node=True)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 475, in dispatch_subgraph
    callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 506, in dispatch_node
    sdfg, dfg, state_id, node, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 148, in generate_node
    gen(sdfg, dfg, state_id, node, function_stream, callsite_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 1105, in _generate_Tasklet
    inner_stream,
  File "/home/dominic/work/dace/dace/codegen/targets/target.py", line 625, in dispatch_copy
    function_stream, output_stream)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 418, in copy_memory
    callsite_stream,
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 455, in _emit_copy
    "    " + self.memlet_definition(sdfg, memlet, False, vconn),
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 911, in memlet_definition
    sdfg, memlet, output) + ";\n")
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 1039, in memlet_ctor
    return self.memlet_view_ctor(sdfg, memlet, is_output)
  File "/home/dominic/work/dace/dace/codegen/targets/cpu.py", line 853, in memlet_view_ctor
    format(memlet_name, def_type))
dace.codegen.codegen.CodegenError: Cannot offset address of connector fill_in of type DefinedType.Scalar

**Comment by tbennun** [comment]
Thanks, the issue is clear now.

**Comment by tbennun** [comment]
@PanicSheep Did the issue resolve with #334 ?
