### ISSUE TITLE
MPI test fails sporadically

### ISSUE THREAD

**Issue by definelicht** [spcl/dace#69]
When multiple tests are running in Jenkins concurrently, the MPI test can fail sporadically. This shows up as false negatives for commits/pull requests that don't actually contain any _new_ bugs.

```
/opt/mpich3.2.11/bin/mpirun
Running python3
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/dace_intel_fpga/tests/../tests/immaterial_test.py", line 4, in <module>
    import dace
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/__init__.py", line 4, in <module>
    from .frontend.python.decorators import *
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/frontend/python/decorators.py", line 7, in <module>
    from dace.frontend.python import parser
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/frontend/python/parser.py", line 8, in <module>
    from dace.config import Config
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/config.py", line 266, in <module>
    Config.initialize()
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/config.py", line 89, in initialize
    Config.load()
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/config.py", line 111, in load
    Config._config_metadata['required'])
  File "/var/lib/jenkins/workspace/dace_intel_fpga/dace/config.py", line 24, in _add_defaults
    if k not in config:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by tbennun** [comment]
Hopefully fixed now
